[package]
name = "tor-stream"
version = "0.1.0"
authors = ["Draphar <draphar-code@protonmail.com>"]
edition = "2018"
description = "Rust interface for proxying network streams over the Tor network"
license = "MIT"

[dependencies]
lazy_static = "1.2.0"
socks = "0.3.0"